Language about security risks
w3c/trace-context pull request #157
Opened 2018-08-13 19:47 UTC by SergeyKanzhelev

#55

2018-08-13 20:18 UTC, yurishkuro commented on trace_context/security.md
> +When distributed tracing was enabled on a service with a public API and naively continue any trace with
s/was/is/

2018-08-13 20:19 UTC, yurishkuro commented on trace_context/security.md
> +it more likely for services to get these attacks.
why does it make it more likely?  The exact same risks exist today. Obscurity is not security.

2018-08-13 20:21 UTC, yurishkuro commented on trace_context/security.md
> +Even though the risk is minimal, application owner should make sure to control the boundary of organization's administrative
> Even though the risk is minimal

is an opinion, why do we need to state it?

2018-08-13 20:21 UTC, yurishkuro commented on trace_context/security.md
> +control. Tracing vendors and platforms should allow to control any unintentional propagation of distributed tracing context.
"control ... administrative  control" - could you please restate this more clearly?

2018-08-13 20:23 UTC, yurishkuro commented on trace_context/security.md
> +the sampling flag set using the `trace-id` provided via `traceparent` field, a malicious attacker could overwhelm an
"set using the `trace-id`" not necessary (makes it hard to read)

2018-08-13 20:23 UTC, yurishkuro commented on trace_context/security.md
> +When distributed tracing was enabled on a service with a public API and naively continue any trace with
s/naively continue/naively continues/

2018-08-13 22:03 UTC, SergeyKanzhelev commented on trace_context/security.md
> +it more likely for services to get these attacks.
The point here is that it is more likely to have generic attacks for standard headers than special attack for specialized `B2` or .NET headers. Like everybody tries to access wordpress admin portal to every domain without even checking. Do you think I can express this though clearer?

2018-08-13 22:41 UTC, mtwo commented on trace_context/security.md
> +it more likely for services to get these attacks.
Perhaps we could reword the last sentence to "Having a standard for context propagation provides attackers with a known way of triggering tracing within an application"

2018-08-13 22:42 UTC, mtwo commented on trace_context/security.md
> +Even though the risk is minimal, application owner should make sure to control the boundary of organization's administrative
Agreed, though I don't think it's a big deal. We can remove "Even though the risk is minimal"

2018-08-13 22:44 UTC, mtwo commented on trace_context/security.md
> +Even though the risk is minimal, application owner should make sure to control the boundary of organization's administrative
Also, "application owner" should be changed to "application owners"

2018-08-13 22:47 UTC, mtwo commented on trace_context/security.md
> +Even though the risk is minimal, application owner should make sure to control the boundary of organization's administrative
Let's change the paragraph to "Application owners should either ensure that no proprietary or confidential information is stored into the tracestate, or they should ensure that tracestate isn't present in requests to external systems".

2018-08-13 22:48 UTC, mtwo requested changes
I made some comments requesting minor changes, looks good otherwise

2018-08-14 16:42 UTC, yurishkuro commented on trace_context/security.md
> +example, browsers single page applications it is typical to make cross-origin calls from the browser. If one of code path leads
> browsers single page applications it is typical

something's off here

2018-08-14 16:42 UTC, yurishkuro commented on trace_context/security.md
> +example, browsers single page applications it is typical to make cross-origin calls from the browser. If one of code path leads
> If one of code path leads

paths

2018-08-14 17:45 UTC, mtwo commented
I went through the security.md file and updated the grammar

2018-08-14 17:45 UTC, mtwo approved these changes

2018-08-14 17:46 UTC, merged