added potential privacy risk
w3c/trace-context pull request #258
Opened 2019-02-27 00:13 UTC by SergeyKanzhelev

This is hypotethical privacy concern in the response headers. During privacy review there was a note that we need to add it. https://github.com/w3c/trace-context/issues/209

I believe it can be moved to the next milestone.

2019-03-01 22:28 UTC, mtwo requested changes

2019-03-01 22:28 UTC, mtwo commented on spec/50-privacy.md
> +In implementations where headers `traceparent` and `tracestate` used as response
Grammar changes:

In implementations where headers `traceparent` and `tracestate` are included in responses, these values may inadvertently be passed to cross-origin callers. Implementations should ensure that they only include these response headers when responding to systems that participated in the trace.

2019-03-12 18:30 UTC, subvocal approved these changes
LGTM

2019-03-22 19:58 UTC, mtwo approved these changes

2019-03-26 17:38 UTC, AloisReitbauer approved these changes

2019-03-26 17:38 UTC, AloisReitbauer commented on spec/50-privacy.md
> +In implementations where headers traceparent and tracestate are included in
the traceparent and tracestate headers

2019-03-26 18:33 UTC, plehegar commented
(waiting on #260 for merge)

2019-03-26 19:28 UTC, nikmd23 approved these changes
There's a nit that could be improved, but I approve.

2019-03-26 19:28 UTC, nikmd23 commented on spec/50-privacy.md
> +In implementations where headers traceparent and tracestate are included in
Agreed with @AloisReitbauer. Here's the suggested cleanup:

```suggestion
In implementations where `traceparent` and `tracestate` headers are included in
```

2019-04-01 17:55 UTC, merged