Changes `recorded` to `sampled`
w3c/trace-context pull request #302
Opened 2019-05-20 16:40 UTC by danielkhan

As discussed in #265

2019-05-20 18:32 UTC, yurishkuro approved these changes

2019-05-21 06:50 UTC, discostu105 approved these changes

2019-05-21 06:52 UTC, discostu105 commented
This will partly conflict with (also valid) changes from @arminru in #288. Can you incorporate those improvements directly in this PR (#288 already has approvals).

2019-05-21 08:35 UTC, danielkhan commented
> This will partly conflict with (also valid) changes from @arminru in #288. @danielkhan can you incorporate those improvements directly in this PR (#288 already has approvals).

I commented on #288 as the whole section is redundant to the processing model. Feel free to add your thoughts there.

2019-05-21 17:46 UTC, SergeyKanzhelev commented
in this PR I think this instance of word `recorded` should be replaced to `sampled`:

```
Value = 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01
base16(version) = 00
base16(trace-id) = 4bf92f3577b34da6a3ce929d0e0e4736
base16(parent-id) = 00f067aa0ba902b7
base16(trace-flags) = 01  // recorded
```

2019-05-21 17:48 UTC, SergeyKanzhelev requested changes
Also change in security section https://w3c.github.io/trace-context/#security-considerations

2019-05-21 17:48 UTC, SergeyKanzhelev commented on spec/20-http_header_format.md
> +   `sampled` flag update. See details of the [`sampled` flag](#recorded-flag-00000001)
```suggestion
   `sampled` flag update. See details of the [`sampled` flag](#sampled-flag-00000001)
```

2019-05-22 16:00 UTC, SergeyKanzhelev approved these changes

2019-05-24 21:30 UTC, nikmd23 approved these changes

2019-05-29 04:49 UTC, merged