Updated tracestate to specify that it should not be used for application level properties
w3c/trace-context pull request #458
Opened 2021-07-14 18:05 UTC by kalyanaj

Updated tracestate section to specify that it should not be used for application level properties. Resolves #439.

2021-07-14 18:09 UTC, yurishkuro approved these changes

2021-07-22 23:23 UTC, Kanwaldeep approved these changes

2021-07-23 00:39 UTC, SergeyKanzhelev requested changes
specs links must be done differently. Also, normative section cannot refer to WD documents

2021-07-23 00:42 UTC, SergeyKanzhelev commented
> specs links must be done differently. Also, normative section cannot refer to WD documents

for example see how `[[!RFC5234]]` is referenced. @plh can help.

I think at this stage we may include this note into the informative header processing section

2021-07-23 00:56 UTC, kalyanaj commented
> > specs links must be done differently. Also, normative section cannot refer to WD documents
> 
> for example see how `[[!RFC5234]]` is referenced. @plh can help.
> 
> I think at this stage we may include this note into the informative header processing section

Good points, thanks Sergey for pointing this out. Would "http_header_format_rationale.md" (I am assuming you are referring to that above) be a good non-normative place to add this information?  I will look at that one and will move it there, and will figure out how to reference the spec link.

2021-07-23 01:23 UTC, SergeyKanzhelev commented
I meant this one: https://github.com/w3c/trace-context/blob/0d32b21bf4d5e1b8cbbbac71a7124471989443fa/index.html#L103

2021-07-29 01:37 UTC, kalyanaj commented
> I meant this one:
> 
> https://github.com/w3c/trace-context/blob/0d32b21bf4d5e1b8cbbbac71a7124471989443fa/index.html#L103

Thanks, I checked the 30-processing-model.md file, but I am not sure if this info about trace-state fits well with the flow there. I was thinking that maybe we should remove the link to the baggage spec from this for now (since it is WD), and instead just retain only the first line i.e. "The `tracestate` HTTP header MUST NOT be used for _application_ level properties such as userId." in the original file (20-http_request_header_format.md) as part of the tracestate header description.

2021-07-29 01:45 UTC, yurishkuro commented
> maybe we should remove the link to the baggage spec from this for now (since it is WD)

I wouldn't. What's the harm in referencing it? Could say "provides a proposal" instead of "provides the specification"

2021-08-03 17:53 UTC, SergeyKanzhelev commented
> > maybe we should remove the link to the baggage spec from this for now (since it is WD)
> 
> I wouldn't. What's the harm in referencing it? Could say "provides a proposal" instead of "provides the specification"

I think the problem of normative spec referencing work in progress is that work in progress may change direction (potentially). Even links to the non-specifications are not well-recieved, Ideally all "dependencies" needs to be stable so over time the meaning of a spec is not changing.

2021-08-03 17:57 UTC, SergeyKanzhelev requested changes
> The `tracestate` HTTP header MUST NOT be used for _application_ level properties such as userId."

My problem is that without the link to spec, that explains more about what "application level properties" are, we need more explanaition in the spec. Why `trace-id` is not application level for instance? Is `application-id` or "cluster" an applicaton level property? I know some vendors want to propagate the "cluster" or "application-id" which help to route traces to the right trace backend "bucket"

2021-08-17 19:20 UTC, plehegar commented on spec/20-http_request_header_format.md
> +The `tracestate` HTTP header MUST NOT be used for _application_ level properties such as userId. [W3C baggage](https://github.com/w3c/baggage) provides the specification for defining and propagating
```suggestion
The `tracestate` HTTP header MUST NOT be used for _application_ level properties such as userId. [W3C baggage](https://github.com/w3c/baggage) MAY be used for defining and propagating application level properties.
```

2021-08-17 19:26 UTC, plehegar commented on spec/20-http_request_header_format.md
> +The `tracestate` HTTP header MUST NOT be used for _application_ level properties such as userId. [W3C baggage](https://github.com/w3c/baggage) provides the specification for defining and propagating
Note that the reference will work once Baggage is published (this Thursday)

2021-08-27 17:44 UTC, dyladan commented on spec/20-http_request_header_format.md
> +The `tracestate` HTTP header MUST NOT be used for any properties that are not defined by a tracing vendor. [[BAGGAGE]] MAY be used for defining and propagating such application level properties.
We should avoid the term "vendor" where possible as we may be used by open source tools too. I would use the word "telemetry system" or similar

2021-08-31 17:44 UTC, dyladan approved these changes

2021-08-31 19:22 UTC, SergeyKanzhelev commented on spec/20-http_request_header_format.md
> +The `tracestate` HTTP header MUST NOT be used for any properties that are not defined by a telemetry system. [[BAGGAGE]] MAY be used for defining and propagating such application level properties.
```suggestion
The `tracestate` HTTP header MUST NOT be used for any properties that are not defined by a tracing system. [[BAGGAGE]] MAY be used for defining and propagating such application level properties.
```

We call it "tracing systems"

2021-08-31 20:38 UTC, SergeyKanzhelev approved these changes

2021-08-31 21:41 UTC, merged